/* Our Town service worker. A classic script (Safari 16 has no module
   workers), ES5-ish on purpose. Pattern from kids-arcade (games/sw.js), with
   one deliberate difference, the P1.2 ruling on updates:

   - A new version installs and precaches in the background, then WAITS. It
     never takes over mid-play (a code swap under a running world could corrupt
     state and would confuse the kids).
   - It activates on the next cold launch: either the browser does it because
     no page is left open, or src/pwa.js sees a waiting worker right at boot
     and sends 'skipWaiting' before anything is played.
   - Or right away when a parent taps "Update now" (pwa.js updateNow()).

   The version is the cache name suffix (cache "ourtown-<VERSION>"), shown in
   the parent menu. VERSION and FILES are generated by `python3 tools/build.py
   precache` from the shipped files; don't edit that block by hand. */

// BEGIN PRECACHE (generated by tools/build.py precache; do not edit)
var VERSION = '51ca7546a8';
var FILES = [
  "./",
  "./assets/icons/icon-180.png",
  "./assets/icons/icon-192.png",
  "./assets/icons/icon-512.png",
  "./index.html",
  "./manifest.webmanifest",
  "./src/app.css",
  "./src/audio/clips.js",
  "./src/audio/context.js",
  "./src/audio/index.js",
  "./src/audio/sfx.js",
  "./src/audio/speech.js",
  "./src/core/persist.js",
  "./src/engine/authority.js",
  "./src/engine/camera.js",
  "./src/engine/ids.js",
  "./src/engine/input.js",
  "./src/engine/ops.js",
  "./src/engine/random.js",
  "./src/engine/stage.js",
  "./src/engine/store.js",
  "./src/engine/world.js",
  "./src/main.js",
  "./src/pwa.js",
  "./src/scenes/boot.js",
  "./src/scenes/input-demo.js"
];
// END PRECACHE

var CACHE_PREFIX = 'ourtown-';
var CACHE = CACHE_PREFIX + VERSION;

/* On the dev server (localhost and friends) go to the network first so edits
   show up on reload without a rebuild; the cache is only the offline fallback.
   Everywhere else it's cache-first, which is what the iPad runs. */
var DEV_HOST = /^(localhost|127\.0\.0\.1|\[::1\])$|\.localhost$|\.test$/.test(self.location.hostname);

self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open(CACHE).then(function (c) {
      // One missing file shouldn't fail the whole install, but the menu should
      // know: record "got/total" so a parent can see it's road-trip ready.
      // cache: 'reload' skips the HTTP cache so we never "install" a stale copy.
      var got = 0;
      return Promise.all(FILES.map(function (f) {
        return c.add(new Request(f, { cache: 'reload' })).then(function () { got++; }, function () {});
      })).then(function () {
        return c.put('./__precache', new Response(got + '/' + FILES.length, { headers: { 'Content-Type': 'text/plain' } }));
      });
    })
    // No skipWaiting() here: see the header comment.
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.map(function (k) {
        return k.indexOf(CACHE_PREFIX) === 0 && k !== CACHE ? caches.delete(k) : null;
      }));
    }).then(function () {
      // Only ever reached on first install (nothing was controlling the page,
      // so claiming it swaps nothing) or when a new version is allowed to take
      // over (cold launch or "Update now").
      return self.clients.claim();
    })
  );
});

self.addEventListener('message', function (e) {
  var data = e.data || {};
  if (data.type === 'skipWaiting') {
    self.skipWaiting();
  } else if (data.type === 'version' && e.ports && e.ports[0]) {
    e.ports[0].postMessage({ version: VERSION });
  }
});

function fromCache(req) {
  // ignoreSearch so "index.html?x" still works offline; navigations to the
  // folder fall back to the cached index.html.
  return caches.open(CACHE).then(function (c) {
    return c.match(req, { ignoreSearch: true }).then(function (hit) {
      if (hit || req.mode !== 'navigate') return hit;
      return c.match('./index.html');
    });
  });
}

function fromNetwork(req) {
  return fetch(req).then(function (res) {
    // Keep a copy of anything fetched at runtime (e.g. a file added since the
    // last precache) so it works offline next time.
    if (res && res.status === 200 && res.type === 'basic') {
      var copy = res.clone();
      caches.open(CACHE).then(function (c) { return c.put(req, copy); });
    }
    return res;
  });
}

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;

  var res = DEV_HOST
    ? fromNetwork(req).catch(function () { return fromCache(req); })
    : fromCache(req).then(function (hit) { return hit || fromNetwork(req); });
  e.respondWith(res.then(function (r) { return r || Response.error(); }));
});
