// Builds the character rig data (assets/characters/rig.json) that the runtime
// assembler src/engine/rig-svg.js turns into live SVG. Contract: docs/rig.md.
import { ART_SCALE, INK_W, css, scaleStrokes, SKINS, SKIN_ORDER, HAIRS, HAIR_ORDER as HAIR_COLOR_ORDER } from '../palette.mjs';
import { f } from '../ink.mjs';
import { BODIES, baseParts, skeleton } from './body.mjs';
import { faceAtoms, EXPRESSIONS, BLINK } from './faces.mjs';
import { HAIR_STYLES, FACIAL_HAIR, HAIR_ORDER, FACIAL_ORDER } from './hair.mjs';
import { WEAR, SLOTS, WEAR_ORDER, OUTFIT_COLORS } from './wear.mjs';
import { POSES } from './poses.mjs';
import { CAST } from './cast.mjs';

const K = ART_SCALE;   // live SVG: 1 art unit = 0.7 CSS px, so strokes scale by 0.7

/** Scale strokes in every string of a nested object. */
function scaleAll(o) {
  if (typeof o === 'string') return scaleStrokes(o, K);
  if (Array.isArray(o)) return o.map(scaleAll);
  if (o && typeof o === 'object') return Object.fromEntries(Object.entries(o).map(([k, v]) => [k, scaleAll(v)]));
  return o;
}

export function buildRig() {
  const bodies = {};
  for (const [id, b] of Object.entries(BODIES)) {
    const base = baseParts(b);
    const sx = f(b.head.rx / 80), sy = f(b.head.ry / 78);
    const hs = (svg) => (svg ? `<g transform="scale(${sx} ${sy})">${svg}</g>` : '');
    const hair = {};
    for (const [hid, h] of Object.entries(HAIR_STYLES)) {
      hair[hid] = { front: hs(h.front), back: h.back ? hs(h.back.svg) : '', backKind: h.back ? h.back.kind : null };
    }
    const facialHair = {};
    for (const [fid, fn] of Object.entries(FACIAL_HAIR)) facialHair[fid] = typeof fn === 'function' ? fn(b.face, b.head) : fn;
    const wear = {};
    for (const [wid, w] of Object.entries(WEAR)) wear[wid] = w.gen(b);
    const { chinRel, ...parts } = base;
    bodies[id] = scaleAll({
      label: b.label,
      skeleton: skeleton(b),
      head: { rx: b.head.rx, ry: b.head.ry },
      parts,
      face: faceAtoms(b.face),
      hair, facialHair, wear,
    });
  }
  const wear = Object.fromEntries(Object.entries(WEAR).map(([id, w]) => [id, { slot: w.slot, label: w.label, hides: w.hides || [], colors: w.colors }]));
  return {
    schema: 1,
    note: 'Generated by tools/art/build.mjs from tools/art/characters/*. Contract: docs/rig.md. Do not edit by hand.',
    artScale: ART_SCALE,
    inkWorld: +(INK_W * ART_SCALE).toFixed(2),
    css: css(K),
    slots: SLOTS,
    expressions: EXPRESSIONS,
    blink: BLINK,
    poses: POSES,
    wear,
    hairStyles: Object.fromEntries(Object.entries(HAIR_STYLES).map(([k, h]) => [k, { label: h.label }])),
    bodies,
    characters: CAST,
    // The Character Maker's choices (P1.15), in button order.
    maker: {
      bodies: ['kid5', 'kid9', 'teen', 'adult', 'elder'],
      skins: SKIN_ORDER.map((k) => SKINS[k]),
      hairColors: HAIR_COLOR_ORDER.map((k) => HAIRS[k]),
      hairStyles: HAIR_ORDER,
      facialHair: FACIAL_ORDER,
      eyes: [null, 'big', 'small', 'almond'],
      brows: [null, 'thin', 'soft', 'bold'],
      wear: WEAR_ORDER,
      outfitColors: OUTFIT_COLORS,
    },
  };
}
